services:
  mysql:
    image: mysql:8.0
    container_name: trabalhoPV
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trabalhoPV
    ports:
      - "3306:3306"
    volumes:
      - mysql-dados:/var/lib/mysql

volumes:
  mysql-dados: